### ISSUE TITLE
Criar modelagem do banco de dados - Sistema de usuário

### ISSUE THREAD

**Issue by byronkamal** [mecassauro/covinfo-backend#22]
**Descrição**
Agora com o novo repositório de backend criado, é necessário criar uma nova modelagem de dados para a nova funcionalidade do **Sistema de usuário Cidadão** (issues #6 #5 ), no qual o cidadão (usuário) poderá fazer o login na aplicação e cadastrar suas informações pessoais que são pedidas pela UPA. 

**Tarefas**
- [x] Identificar entidades e seus atributos
- [x] Identificar os ralacionamentos entre as entidades
- [x] Acrescentar imagem do diagrama lógico nesta issue

**Comment by pAmanda** [comment]
Nos reunimos no dia 08/10/20 de 21h ás 23h00 para criar a modelagem do banco para o cadastro de usuários do sistema. Abaixo está o modelo final.

![modelagem](https://user-images.githubusercontent.com/23346202/95918140-a7ace400-0d81-11eb-9d56-354074ae8d42.png)
