### ISSUE TITLE
Envio de email e recuperação de senha

### ISSUE THREAD

**Issue by LuisCL94** [mecassauro/covinfo-backend#26]
**Descrição**

O usuário deve conseguir recuperar sua senha ao receber intruções por email;

**Tarefas**
- [x] Configurar envio de emails;
- [x] Criar templates html para reset de senha;
- [x] Configurar fila para envio de email em segundo plano;
- [x] Usuário deve poder recuperar sua senha informando seu e-mail;
- [x] Enviar e-mail para o usuário com instruções para recuperação de senha;
- [x] Recuperar senha de usuário seguido instruções enviadas para seu email;

**Contexto adicional**
 - Utilizar EtherealMail para testar envio de e-mail;
 - O link enviado por e-mail para resetar senha deve expirar em 3h;

**Comment by pAmanda** [comment]
Para desenvolver essa issue, precisamos adicionar uma nova tabela ao banco de dados chamada NOTIFICATION. Na imagem abaixo está a modelagem final:

![modelagem](https://user-images.githubusercontent.com/23346202/97512195-ad9cea80-1967-11eb-8cc3-4049769bed9c.png)
