### ISSUE TITLE
Erro - User_id not-null

### ISSUE THREAD

**Issue by paulohenriquerosa** [mecassauro/covinfo-backend#62]
**Descrição do bug**

A inicializar pela segunda vez o backend é retornado o seguinte erro:

_ERROR: null value in column "user_id" violates not-null constraint_

**Como reproduzir**

Passos para reproduzir o comportamento:
1. Na pasta raiz do projeto execute o comando _docker-compose build && docker-compose up_
2. Crie um novo usuário com a rota http://localhost:3333/users
2. Quando inicializar o backend execute o comando _docker-compose down_
3. Novamente execute o comando _docker-compose up_
4. Veja o erro

**Comportamento esperado**

O backend deve poder inicializar normalmente independentemente de quantas vezes for inicializado.

**Capturas de telas**
Imagem do erro recebido:
![image](https://user-images.githubusercontent.com/33530625/100864375-abe9a980-3474-11eb-87a0-03dd5b9301e4.png)

**Desktop (preencha as seguintes informações):**
 - OS: Ubuntu 20.04

**Informações adicionais**

Um possível explicação é que ao criar um novo usuário não está sendo preenchido um coluna não nula no banco de dados.

**Comment by IgorVeludo2** [comment]
Problema era dentro da migration de login. Dentro da chave estrangeira user_id, a propriedade onDelete estava setado como 'SET_NULL', o mais adequado seria 'CASCADE'. Com essa modificação, o problema desse bug foi resolvido.
![image](https://user-images.githubusercontent.com/22936236/101421069-482b0a80-38d2-11eb-8e9b-7b71ef0c3ff0.png)
